# Generated by Django 4.2.5 on 2024-03-31 03:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stream.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VidRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=600)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('permission', models.IntegerField(choices=[(1, 'Sender'), (2, 'Receiver'), (3, 'Admin')], default=1)),
                ('security_question', models.IntegerField(choices=[(1, 'What was the name of your first pet?'), (2, 'In which city were you born?'), (3, 'What is the middle name of your oldest sibling?'), (4, 'What is the name of your favorite sports team?'), (5, 'What was the make and model of your first car?')], default=1)),
                ('security_answer', models.CharField(default=' ', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkmode', models.BooleanField(default=False)),
                ('emailnotification', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='mountain.jpg', storage=stream.storage_backends.ProfilePictureStorage(), upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=600)),
                ('sendtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('timelimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.URLField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_receiver', to=settings.AUTH_USER_MODEL)),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidstream')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, 'Friend Request Send'), (2, 'Accept/Reject Friend Request'), (3, 'Video Request Send'), (4, 'Video Request Receive'), (5, 'Post Upload'), (6, 'Post Receive'), (7, 'Video Upload'), (8, 'Text')], null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('friendRequest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.friendrequest')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoRequest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.vidrequest')),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidstream')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
