# Generated by Django 4.2.5 on 2024-03-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_friendrequest_remove_vidstream_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidstream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vidstream',
            name='title',
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
