# Generated by Django 4.2.5 on 2024-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_remove_vidstream_description_remove_vidstream_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
